CREATE OR REPLACE
PACKAGE BODY HR_DATA AS

  PROCEDURE GET_EMPLOYEE_RECORDS(department_id  IN NUMBER, EMPLOYEES_C OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN EMPLOYEES_C FOR SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = GET_EMPLOYEE_RECORDS.DEPARTMENT_ID;
  END GET_EMPLOYEE_RECORDS;

END HR_DATA;
